name: 'SSH Remote Commands'
description: 'Execute commands on a remote server via SSH with key-based authentication, environment variable forwarding, and timeout control.'
author: 'CaeliCode'

branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  host:
    description: 'SSH server hostname or IP address. Supports multiple hosts separated by commas for sequential execution.'
    required: true
  port:
    description: 'SSH server port'
    required: false
    default: '22'
  username:
    description: 'SSH username for authentication'
    required: true
  password:
    description: 'SSH password (prefer key-based auth when possible)'
    required: false
    default: ''
  key:
    description: 'SSH private key content (e.g. from secrets.SSH_PRIVATE_KEY). Supports RSA, ED25519, and ECDSA keys.'
    required: false
    default: ''
  envs:
    description: 'Comma-separated list of environment variable names to forward to the remote host'
    required: false
    default: ''
  script:
    description: 'Shell commands to execute on the remote server'
    required: false
    default: ''
  script_file:
    description: 'Path to a local script file to execute on the remote server (alternative to inline script)'
    required: false
    default: ''
  remote_shell:
    description: 'Shell to use on the remote server (e.g. bash, sh, zsh)'
    required: false
    default: 'bash'
  connect_timeout:
    description: 'SSH connection timeout in seconds'
    required: false
    default: '30'
  command_timeout:
    description: 'Maximum execution time for the remote script in seconds (0 = no limit)'
    required: false
    default: '600'
  fingerprint:
    description: 'SHA256 fingerprint of the host key for strict verification (e.g. SHA256:xxx). If not set, uses accept-new policy.'
    required: false
    default: ''
  proxy_host:
    description: 'Jump/bastion host for proxied connections'
    required: false
    default: ''
  proxy_port:
    description: 'Jump host SSH port'
    required: false
    default: '22'
  proxy_username:
    description: 'Jump host username'
    required: false
    default: ''
  proxy_key:
    description: 'Jump host SSH private key content'
    required: false
    default: ''
  request_pty:
    description: 'Request a pseudo-terminal on the remote server'
    required: false
    default: 'false'
  args:
    description: 'Additional SSH client arguments (e.g. -v for verbose)'
    required: false
    default: ''

outputs:
  stdout:
    description: 'Standard output captured from the remote commands'
    value: ${{ steps.ssh.outputs.stdout }}

runs:
  using: 'composite'
  steps:
    - name: Execute SSH commands
      id: ssh
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        INPUT_HOST: ${{ inputs.host }}
        INPUT_PORT: ${{ inputs.port }}
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_KEY: ${{ inputs.key }}
        INPUT_ENVS: ${{ inputs.envs }}
        INPUT_SCRIPT: ${{ inputs.script }}
        INPUT_SCRIPT_FILE: ${{ inputs.script_file }}
        INPUT_REMOTE_SHELL: ${{ inputs.remote_shell }}
        INPUT_CONNECT_TIMEOUT: ${{ inputs.connect_timeout }}
        INPUT_COMMAND_TIMEOUT: ${{ inputs.command_timeout }}
        INPUT_FINGERPRINT: ${{ inputs.fingerprint }}
        INPUT_PROXY_HOST: ${{ inputs.proxy_host }}
        INPUT_PROXY_PORT: ${{ inputs.proxy_port }}
        INPUT_PROXY_USERNAME: ${{ inputs.proxy_username }}
        INPUT_PROXY_KEY: ${{ inputs.proxy_key }}
        INPUT_REQUEST_PTY: ${{ inputs.request_pty }}
        INPUT_ARGS: ${{ inputs.args }}
